[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nipoppy"
authors = [{ name = "nikhil153" }]
version = "0.2.0"  # TODO eventually use dynamic versioning

dependencies = [
]

[project.optional-dependencies]
test = ["pytest"]

# alias in case of typo
tests = ["nipoppy[test]"]

[tool.hatch.build.targets.wheel]
packages = ["nipoppy"]

[tool.codespell]
skip = '.git,.github,pyproject.toml'

[tool.pytest.ini_options]
addopts = "-ra -q -vv "
testpaths = ["tests/"]
