[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "nipoppy"
authors = [{ name = "nikhil153" }]
version = "0.1.0"

dependencies = [
    "pandas",
    "numpy",
    "joblib",
    "pydicom",
    "nibabel",
    "pybids",
    "requests",
]

[tool.hatch.build.targets.wheel]
packages = ["nipoppy"]

[project.optional-dependencies]
test = ["pytest"]

[tool.codespell]
skip = '.git,.github,*.pdf,*.svg,pyproject.toml'
ignore-words-list = 'te,ines'

[tool.pytest.ini_options]
addopts = "-ra -q -vv "
testpaths = ["tests/"]