---
name: test

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:

    runs-on: ubuntu-latest

    # only trigger on upstream repo
    # if: github.repository_owner == 'neurodatascience' && github.repository == 'nipoppy' 

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install 
      run: |
        pip install -U pip
        pip install .[tests]

    - name: Test
      run: |
        pytest tests/tests_workflow_fmriprep.py